<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '\'{attribute}\' does not support operator \'{operator}\'.' => '',
    'Condition for \'{attribute}\' should be either a value or valid operator specification.' => '',
    'Operator \'{operator}\' must be used with a search attribute.' => '',
    'Operator \'{operator}\' requires multiple operands.' => '',
    'The format of {filter} is invalid.' => '',
    'Unknown filter attribute \'{attribute}\'' => '',
];
